# Generated by Django 2.1 on 2018-09-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='visible_name',
        ),
        migrations.RemoveField(
            model_name='productsex',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productsubsubcategory',
            name='position',
        ),
    ]
