# Generated by Django 2.1 on 2018-09-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180918_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsex',
            name='visible_name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='visible_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
