# Generated by Django 2.1 on 2018-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180918_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
