# Generated by Django 2.1 on 2018-09-20 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_auto_20180919_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='more_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='specification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='count_size_l',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='count_size_m',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductItem'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
