# Generated by Django 2.1 on 2018-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180920_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='more_information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='specification',
            field=models.TextField(),
        ),
    ]
