# Generated by Django 2.1 on 2018-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180921_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.Tags'),
        ),
    ]
