# Generated by Django 2.1 on 2018-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180921_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsubsubcategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
