# Generated by Django 2.1 on 2018-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180922_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='featured_colection',
            field=models.BooleanField(default=False),
        ),
    ]
