# Generated by Django 2.1 on 2018-09-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_productitem_featured_colection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='featured_colection',
            new_name='featured_collection',
        ),
    ]
