# Generated by Django 2.1 on 2018-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_productitem_made_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='made_in',
            field=models.CharField(max_length=32),
        ),
    ]
