# Generated by Django 2.1 on 2018-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20180923_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='fabric_origin',
            field=models.CharField(default='Italy', max_length=32),
        ),
    ]
