# Generated by Django 2.1 on 2018-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_productitem_fabric_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='fabric_origin',
            field=models.CharField(max_length=32),
        ),
    ]
