# Generated by Django 2.1 on 2018-09-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20180923_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='color',
            field=models.CharField(default='White', max_length=32),
        ),
    ]
